### ISSUE TITLE
US#1 List of Exercises for biceps

### ISSUE THREAD

**Issue by esrefbozkurt** [esrefbozkurt/capstone-project#1]
## Value Proposition

**As a** ...fitness enthusiast

**I need** ...to see a list of exercises for one muscle group

**to be able to** ...get an overview of all available exercises 
## Description

Scribble / design or text
![image](https://user-images.githubusercontent.com/113592929/207047272-03c470f1-e785-4e5d-b65c-953d5135cfa5.png)

## Acceptance Criteria

- [ ] the name of the App is displayed in the heading 
- [ ] the "muscle group Exercises" header is displayed under the heading
- [ ] all exercises are displayed in boxes 
- [ ] overflow is scrollable

## Tasks

- [ ] work on branch
- [ ] components Exercises
- [ ] (Storybook)
- [ ] testing
- [ ] create Header for exercises with muscle group name 
- [ ] create dummy data
- [ ] creating a list of boxes of exercises by mapping through dummy data 
- [ ] basic styling components

**Comment by julialoeschel** [comment]
🔥  good to go! very good story!
