### ISSUE TITLE
US#10 add exercises to workouts

### ISSUE THREAD

**Issue by esrefbozkurt** [esrefbozkurt/capstone-project#13]
## Value Proposition

**As a** ...user
**I want to** ...edit the workout card
**so that** ...I can add exercises to my workout
​

## Description

![image](https://user-images.githubusercontent.com/113592929/211481410-b7a097c3-0b49-4c03-8f3d-9272221baf04.png)

​

## Acceptance Criteria

- add button is displayed on the bottom 
- onclick the add button leads to a new page 
- in the new page all exercises are listed starting with the favourite exercises 
- every exercise has a add icon 
- add icon adds exercises to the Workout
      ​

## Tasks

- [ ] new branch
- [ ] component
- [ ] create add button in the workout page
- [ ] new page with all favourite exercises and all exercises are listed 
- [ ] create add button at every exercise 
- [ ] add icon adds exercise to workout and and the added exercise is listed in the Workout page 

      ​

**Comment by Elgin-Schultz** [comment]
Sounds convincing to me. Just for my understanding, you have to put a workout on the favs list to be able to choose. (Don't you have to do workouts even you do not like them so very much?)

**Comment by esrefbozkurt** [comment]
Hey thanks for checking! The exercises are on a fav list. In the mentioned drop menu the user is able check every exercise but the favourite exercises are listed first. The Workouts can only be created on this page so there is no possibility to bookmark them. So you have to create a workout (US#8) to be able to edit it a add exercises as mentioned. Hope its more clear now :)

**Comment by Elgin-Schultz** [comment]
Thank you so much for explaining!
