### ISSUE TITLE
US#6 Connect API and MongoDB

### ISSUE THREAD

**Issue by esrefbozkurt** [esrefbozkurt/capstone-project#17]
## Value Proposition

**As a** ...user

**I need** ...to see all exercises rendered from a server 

**to be able to** ...choose,  exercise i want to work on

## Acceptance Criteria

- the app should be able to use data from the Server 

## Tasks

- [ ] work on branch
- [ ] connect  mongoDB Server
- [ ] create custom api to connect to app

**Comment by ufelgen** [comment]
Hey Eshi, kannst du vielleicht noch ein paar Akzeptanzkriterien aufstellen? z.B. dass die Übersicht über die Muskelgruppen auf der Startseite angezeigt wird (wie im Scribble) und dass die klickbar sind und auf dynamische Seiten führen? oder kommt das hier noch nicht? aber zumindest ein Akzeptanzkriterium würde ich mir einfallen lassen ;) viel Erfolg mit der Datenbank! Da muss ich diese Woche auch noch ran....

**Comment by esrefbozkurt** [comment]
In dieser US soll es rein um die Anbindung des Servers mit den Daten gehen. Dies ist jetzt US 6 in US 7 erfolgt dann der Zugriff auf die Daten und die Kategorien. Ich habe das scribble entfernt. Danke für dein Feedback. :)

**Comment by esrefbozkurt** [comment]
> Hey Eshi, kannst du vielleicht noch ein paar Akzeptanzkriterien aufstellen? z.B. dass die Übersicht über die Muskelgruppen auf der Startseite angezeigt wird (wie im Scribble) und dass die klickbar sind und auf dynamische Seiten führen? oder kommt das hier noch nicht? aber zumindest ein Akzeptanzkriterium würde ich mir einfallen lassen ;) viel Erfolg mit der Datenbank! Da muss ich diese Woche auch noch ran....

In dieser US soll es rein um die Anbindung des Servers mit den Daten gehen. Dies ist jetzt US 6 in US 7 erfolgt dann der Zugriff auf die Daten und die Kategorien. Ich habe das scribble entfernt. Danke für dein Feedback. :)
