### ISSUE TITLE
US#2 Exercises with description 

### ISSUE THREAD

**Issue by esrefbozkurt** [esrefbozkurt/capstone-project#2]
## Value Proposition

**As a** ...user

**I need** ...to see a list of exercises 

**to be able to** ...see the exercises description as a dropdown box

## Description

Scribble / design or text
![image](https://user-images.githubusercontent.com/113592929/207067833-9ada5818-e90a-4bdb-a3a1-9fe4725f2e3d.png)

## Acceptance Criteria
- [ ] every exercise box is displayed with a box  "description"
- [ ] display a description box inside one exercise box with a dropdown-button 
- [ ] after clicking the dropdown-button the exercise box expands on the same page and shows the description with a link for a web search of the exercise
- [ ] after clicking the dropdown-button again the description box collapses

## Tasks

- [ ] work on branch
- [ ] components description
- [ ] (Storybook)
- [ ] testing
- [ ] create a box inside the exercise box with the content "description"
- [ ] create dropdown (toggle - expand and collapse) function which shows the description  groups
- [ ] display description content from dummy data by filter function

**Comment by marvinRoellecke** [comment]
top 🏋️
