### ISSUE TITLE
US #7 List of MuscleGroups 

### ISSUE THREAD

**Issue by esrefbozkurt** [esrefbozkurt/capstone-project#3]
## Value Proposition

**As a** ...user

**I need** ...see all muscle groups

**to be able to** ...choose, which muscle group i want to work on

## Description

Scribble / design or text
<img width="288" alt="Screenshot 2022-12-09 at 16 27 22" src="https://user-images.githubusercontent.com/113592929/206735883-60cf601e-e651-46c6-8708-8f72faf52df1.png">

## Acceptance Criteria

- [ ] the name of the App is displayed in the heading 
- [ ] the "muscle group" header is displayed under the heading
- [ ] all muscle groups are displayed in boxes 
- [ ] every muscle group is displayed with a picture of it 
- [ ] the muscle group is clickable and routes dynamically to the exercises page 
- [ ] overflow is scrollable

## Tasks

- [ ] work on branch
- [ ] component
- [ ] creating category boxes by mapping through data on a new (home)page 
- [ ] Header in Exercise Page should be dynamic
- [ ] add image for every muscle group image
- [ ] basic styling

**Comment by onebarloop** [comment]
Sounds like a very reasonable first step. Good structure, manageable workload.

**Comment by MerleMak** [comment]
Hi Eshi, 
As we talked about, here a quick summary.
You. can use your value proposition to better define your user group. In your example: 
```
As a ..fitness enthusiast
I need to ..see a list of exercises
to be able to ..get ideas/inspirations for my daily workout
```
So my tipp: start smaller!
The main use case for your app at this point will be the list of exercises, so rendering the list is the first thing and build up functionality from this point on. 

Use your dummy data to render a page of exercises (components) of only one muscle group und then add variability (props in components) to it after. 
Only when this list of exercises is ready and generated for all of the muscle groups (for example with dynamic routes) - only then its time to create the overview of all the muscle groups, which you are currently displaying in this user story.

Other than that, your AC and Tasks are great!
Keep it up :))
