### ISSUE TITLE
US#3 Search Bar for Exercises

### ISSUE THREAD

**Issue by esrefbozkurt** [esrefbozkurt/capstone-project#4]
## Value Proposition

**As a** ...  user
**I want to** ...  see a search icon
**to be able to** ...click on it and search for exercises
​

## Description

![image](https://user-images.githubusercontent.com/113592929/207071369-b499a9b0-304e-4fba-94db-d5111bbb2350.png)

​

## Acceptance Criteria

- [ ] create a search bar button next to exercises header
- [ ] after clicking the search-bar icon the search bar appears over the exercises header​
- [ ] in the search bar you can search for exercises, while writing letters suggestions being made

## Tasks

- [ ] work on branch
- [ ] create search bar component
- [ ] create search icon with search bar appearing by clicking the icon
- [ ] add search functionality - searching through all rendered exercises
- [ ] add styling components
      ​

**Comment by muhammed-basaran** [comment]
like the way you thinking. looks very good
