### ISSUE TITLE
US#4 Favorite exercises - bookmarking

### ISSUE THREAD

**Issue by esrefbozkurt** [esrefbozkurt/capstone-project#5]
## Value Proposition

**As a** ...  user
**I want to** ...  bookmark my favorite exercises 
**so that** ...I can save my favorite exercises
​

## Description
![image](https://user-images.githubusercontent.com/113592929/207076943-6ac23583-95f1-4e0a-8464-725453cf2e95.png)
​

## Acceptance Criteria

- [ ] a bookmark icon is displayed in the up right corner of a exercise box
- [ ] it is clickable and changes the color 
      ​

## Tasks

- [ ] work on branch
- [ ] components FavButton
- [ ] (Storybook)
- [ ] testing
- [ ] create a bookmark icon as a button
- [ ] add toggle function to the button for changing the color onClick
      ​

**Comment by NeeleWaehnke** [comment]
Looks very good! :)
