### ISSUE TITLE
US#5 NavBar with favorite page 

### ISSUE THREAD

**Issue by esrefbozkurt** [esrefbozkurt/capstone-project#6]
## Value Proposition

**As a** ...user 
**I want to** ...  see a navigation bar 
**so that** ...I can switch between exercises and favorite exercises 
​

## Description
![image](https://user-images.githubusercontent.com/113592929/207224305-e2f58b8b-698d-4f6c-a74c-b12b3841882c.png)
​

## Acceptance Criteria

- [ ] a navigation bar is displayed  fixed on the bottom
- [ ] in the NavBar there are two button for the exercises page ant the favorite/bookmarked page
- [ ] when clicked the bookmark and the overview icon is filled
- [ ] at the favorite page the header is displayed as "Favorite Exercises"

      ​

## Tasks

- [ ] work on branch
- [ ] component NavBar
- [ ] new page as Favorite component
- [ ] (Storybook)
- [ ] create a NavBar with two buttons as icons 
- [ ] add routing for two pages 
- [ ] create functionality when bookmark is clicked its part of the favorite page

**Comment by muhammed-basaran** [comment]
alles top aber würde den header in der Darstellung wie beschrieben ändern:

**Comment by andy-schwedler** [comment]
> when clicked the button is filled

what exactly do you mean by button? bookmark icon?

**Comment by andy-schwedler** [comment]
> testing

What do you mean by testing? User Acceptance Testing or Unit Tests?

**Comment by esrefbozkurt** [comment]
- Header hast been changed 
- yes i mean the bookmark icon, text hast been changed
- deleted testing task
