### ISSUE TITLE
US#8 Backbutton Exercise to Muscle Group

### ISSUE THREAD

**Issue by esrefbozkurt** [esrefbozkurt/capstone-project#7]
## Value Proposition

**As a** user  
**I want to** i want to get back to the muscle group page after choosing a muscle group 
**so that** ...I can choose a different muscle group and see the related exercises
​

## Description
![image](https://user-images.githubusercontent.com/113592929/208371070-fc132639-2432-49ae-852b-f3621e63f7e6.png)

## Acceptance Criteria

- [ ] button is displayed next to the exercise header
- [ ] on click the button routes you to the muscle overview page 
      ​

## Tasks

- [ ] routing from overview to exercise 
- [ ] add back button icon 
- [ ] back routing on button click
      ​

**Comment by AntjeWalter** [comment]
The second line of the value proposition needs a little change and maybe you could be a little more specific which button is new and on which site it is displayed. Otherwise it's a good US I think :)
