### ISSUE TITLE
US#9 My Workouts and add Workouts

### ISSUE THREAD

**Issue by esrefbozkurt** [esrefbozkurt/capstone-project#8]
## Value Proposition

**As a** ...user
**I want to** ...create own workouts 
**so that** ...i can see my workouts
​

## Description

![image](https://user-images.githubusercontent.com/113592929/211478969-786f1054-5342-425c-b280-89ca7fbb6717.png)

​

## Acceptance Criteria

- plus icon displays a new workout page, where you enter name 
- new Workout page can be added by clicking on the check icon 
- back icon leads back to my workout page
- cancel/delete button on workout card is displayed and deletes the workout 
      ​

## Tasks

- [ ] add button next to "My Workouts"  header
- [ ] create a workout page with a input field for the name of the workout
- [ ] add /create function  on workout page + delete function on the workout card on my workout page 
      ​

**Comment by AntjeWalter** [comment]
Will this be a new page? If yes, this should also be included in the US. Otherwise it's a good and doable User Story 👍
