### ISSUE TITLE
US#12 Form fields for exercise sets 

### ISSUE THREAD

**Issue by esrefbozkurt** [esrefbozkurt/capstone-project#9]
## Value Proposition

**As a** ...user 
**I want to** ...  be able to input reps and sets and some other Information
**so that** ...i can safe my current planned exercise
​

## Description

​
![image](https://user-images.githubusercontent.com/113592929/211484630-45dd427c-2757-4809-9924-0e9f112db831.png)

## Acceptance Criteria

- on click of the  exercise a new page is displayed with current exercise 
- a add set button is displayed on the button where you are able to add new set cards
- the set card has a input field for the set number, the weight, a "x" in between and input field for the reps 
- on the left side of the set header there is a delete icon displayed 
- on the right of the set header is a check icon displayed wich submits the set 
## Tasks

- [ ] work on branch
- [ ] component EditExercise
- [ ] add routing 
- [ ] create a button for adding a set
- [ ] create inputs 
- [ ] function for safe inputs and update data Array
- [ ] function for edit set inputs 
- [ ] function for delete sets

**Comment by NeeleWaehnke** [comment]
Schöne Userstory :)
